### ISSUE TITLE
Week 1 Design Layout & UI/UX data flow

### ISSUE THREAD

**Issue by wattskimzey** [wattskimzey/easywrap#5]
This is required so Chase can deliver the Week 1 Content Delivery to the Overlords.  it includes the detailed screen by screen design layouts with annotations describing the UI/UX data flow layout

**Comment by mek413** [comment]
![image](https://user-images.githubusercontent.com/51460121/71310753-3f010f00-23dd-11ea-9ab8-f587367ef6ee.png)

**Comment by mek413** [comment]
![image](https://user-images.githubusercontent.com/51460121/71310768-67890900-23dd-11ea-96ce-df09096b7dac.png)

**Comment by mek413** [comment]
![image](https://user-images.githubusercontent.com/51460121/71310776-8b4c4f00-23dd-11ea-8f08-2d171a1063da.png)

**Comment by mek413** [comment]
![image](https://user-images.githubusercontent.com/51460121/71310904-7cff3280-23df-11ea-8f88-6ea8271318ea.png)

**Comment by mek413** [comment]
![image](https://user-images.githubusercontent.com/51460121/71311015-b3897d00-23e0-11ea-97ed-e70418efb7d2.png)
